const mongoose = require("mongoose");

const bookingSchema = new mongoose.Schema(
  {
    bookingId: { type: String, required: true, unique: true },
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
    bookingType: { type: String, enum: ["HOTEL", "CAB"], required: true },

    // Hotel Specific
    hotelBooking: {
      hotelId: { type: mongoose.Schema.Types.ObjectId, ref: "Hotel" },
      roomId: { type: mongoose.Schema.Types.ObjectId, ref: "Room" },
      holdId: { type: mongoose.Schema.Types.ObjectId, ref: "BookingHold" },
      checkInDate: Date,
      checkOutDate: Date,
      dates: [Date],
      roomsCount: Number,
      guests: { adults: Number, children: Number },
      guestDetails: {
        fullName: String,
        mobile: String,
        email: String,
        guestCount: Number,
        expectedArrivalTime: String,
        idProofType: String,
        idProofNumber: String,
        additionalGuests: [String],
        specialRequest: String,
        gstDetails: {
          gstNumber: String,
          companyName: String,
        },
      },
      needPickupCab: {
        type: String,
        enum: ["yes", "no", "later"],
        default: "no",
      },
      cancellationReason: String,
      modificationRequest: {
        requestedAt: Date,
        newCheckInDate: Date,
        newCheckOutDate: Date,
        newGuestCount: Number,
        newRoomsCount: Number,
        specialRequest: String,
        status: {
          type: String,
          enum: ["pending", "approved", "rejected"],
        },
        adminResponse: String,
      },
      status: {
        type: String,
        enum: [
          "hold_created",
          "payment_pending",
          "pending_approval",
          "confirmed",
          "checked_in",
          "completed",
          "cancelled",
          "cancellation_requested",
          "rejected",
          "no_show",
          "expired",
          "failed",
        ],
      },
    },

    // Cab Specific
    cabBooking: {
      assignedCabProviderId: { type: mongoose.Schema.Types.ObjectId, ref: "CabVendor" },
      vendorId: { type: mongoose.Schema.Types.ObjectId, ref: "CabVendor" },
      vehicleId: { type: mongoose.Schema.Types.ObjectId, ref: "Vehicle" },
      cabSourcePreference: {
        type: String,
        enum: ["HOTEL_LINKED", "EXTERNAL", "ANY"],
        default: "ANY",
      },
      cabSourceType: { type: String, enum: ["HOTEL_LINKED", "INDEPENDENT"] },
      hotelBookingId: { type: mongoose.Schema.Types.ObjectId, ref: "Booking" },
      hotelId: { type: mongoose.Schema.Types.ObjectId, ref: "Hotel" },
      pickupLocation: {
        address: String,
        placeId: String,
        lat: Number,
        lng: Number,
      },
      dropLocation: {
        address: String,
        placeId: String,
        lat: Number,
        lng: Number,
      },
      pickupDateTime: Date,
      tripType: String,
      passengers: Number,
      luggageCount: Number,
      vehicleType: String,
      distanceKm: Number,
      durationMinutes: Number,
      fareSnapshot: {
        baseFare: Number,
        distanceFare: Number,
        timeFare: Number,
        taxAmount: Number,
        minimumFareApplied: Boolean,
      },
      acceptedAt: Date,
      startedAt: Date,
      completedAt: Date,
      cancelledAt: Date,
      statusLogs: [
        {
          status: String,
          timestamp: Date,
          location: { lat: Number, lng: Number },
        },
      ],
      status: {
        type: String,
        enum: [
          "requested",
          "notified_drivers",
          "external_cabs_notified",
          "hotel_cabs_notified",
          "accepted",
          "assigned",
          "on_the_way",
          "arrived_at_pickup",
          "trip_started",
          "completed",
          "cancelled",
          "rejected",
          "no_driver_found",
          "no_show",
        ],
        default: "requested",
      },
    },

    // Payment Details
    paymentMode: {
      type: String,
      enum: ["online", "pay_at_hotel", "cod", "partial"],
      default: "online",
    },
    paymentStatus: {
      type: String,
      enum: [
        "pending",
        "paid",
        "partially_paid",
        "failed",
        "refund_initiated",
        "refunded",
        "partially_refunded",
        "cod_pending",
        "cod_collected",
      ],
      default: "pending",
    },
    codCollectedBy: { type: mongoose.Schema.Types.ObjectId, ref: "CabVendor" },
    codCollectedAt: Date,
    totalAmount: { type: Number, required: true },
    taxAmount: { type: Number, default: 0 },
    discountAmount: { type: Number, default: 0 },
    couponCode: String,
    couponDiscount: { type: Number, default: 0 },
    platformCommission: { type: Number, default: 0 },
    partnerEarning: { type: Number, default: 0 },
  },
  { timestamps: true },
);

module.exports = mongoose.model("Booking", bookingSchema);
